[pytest]
testpaths = tests
python_files = test_*.py
addopts = -q --strict-markers
filterwarnings =
    ignore::DeprecationWarning:flask_sqlalchemy.*
    ignore:datetime.datetime.utcnow:DeprecationWarning
